server {
    listen 8080;
    server_name nefast.me;
    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }
}
